### ISSUE TITLE
cannot install on ubuntu

### ISSUE THREAD

**Issue by duanrb** [aio-libs/idna-ssl#98]
I'm trying to install idna-ssl on ubuntu 16.04, but I get this error. Thanks a lot for help.

> pip3.6 install idna-ssl

Collecting idna-ssl
  Using cached https://files.pythonhosted.org/packages/46/03/07c4894aae38b0de52b52586b24bf189bb83e4ddabfe2e2c8f2419eec6f4/idna-ssl-1.1.0.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3.6 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-8s8q3slc/idna-ssl/setup.py'"'"'; __file__='"'"'/tmp/pip-install-8s8q3slc/idna-ssl/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-8s8q3slc/idna-ssl/
    Complete output (39 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/ubuntu/.local/lib/python3.6/site-packages/setuptools/__init__.py", line 12, in <module>
        from setuptools.extension import Extension
      File "/home/ubuntu/.local/lib/python3.6/site-packages/setuptools/extension.py", line 7, in <module>
        from setuptools.dist import _get_unpatched
      File "/home/ubuntu/.local/lib/python3.6/site-packages/setuptools/dist.py", line 16, in <module>
        import pkg_resources
      File "/home/ubuntu/.local/lib/python3.6/site-packages/pkg_resources.py", line 1479, in <module>
        register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)
    AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'
    Error in sys.excepthook:
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
        from apport.fileutils import likely_packaged, get_recent_crashes
      File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
        from apport.report import Report
      File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
        import apport.fileutils
      File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
        from apport.packaging_impl import impl as packaging
      File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 23, in <module>
        import apt
      File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
        import apt_pkg
    ModuleNotFoundError: No module named 'apt_pkg'
    
    Original exception was:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/ubuntu/.local/lib/python3.6/site-packages/setuptools/__init__.py", line 12, in <module>
        from setuptools.extension import Extension
      File "/home/ubuntu/.local/lib/python3.6/site-packages/setuptools/extension.py", line 7, in <module>
        from setuptools.dist import _get_unpatched
      File "/home/ubuntu/.local/lib/python3.6/site-packages/setuptools/dist.py", line 16, in <module>
        import pkg_resources
      File "/home/ubuntu/.local/lib/python3.6/site-packages/pkg_resources.py", line 1479, in <module>
        register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)
    AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 19.2.1, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by asvetlov** [comment]
Sorry, seems that something is broken on your system.
`SourceFileLoader` exists in `importlib` starting from Python 3.3.
Upgrading `pip` *may* help.
